<!-- 
 - File: head.inc
 - Author: Kevin Hardy-Cooper
 - Date: March 20, 2018
 - ABSTRACT: Contains common elements related to the head and the beginning of a php page
 -->
<!DOCTYPE html>
	<html>
		<head>

			<!-- Character encoding -->
			<meta charset = "UTF-8"/>

			<!-- Assisting with scaling from desktop to mobile, inspired by https://www.w3schools.com/css/css_rwd_viewport.asp -->
			<meta name = "viewport" content = "width = device-width, initial-scale = 1"/>
			
			<!-- Page author -->
			<meta name = "author" content = "Kevin Hardy-Cooper"/>

			<!-- Title of the page -->
			<title>Farmer's Friend</title>
